# this is an example config
pack:
  # this option enables the core runtime environment that i have built
  # core.js and wasm_decoder for brotli decode of wasm_modules
  runtime:
    enabled: true
  meta:
    title: "hokej"
    author: "me"
    description: "packed by htmlpacker"
    keywords: "hello from yaml"
  css:
    #local:
    #remote:
    #  - "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
  scripts:
    local:
      - "../wasm_modules/pkg/wasm_modules.js"
      - 
  wasm:
    module:
      compile_wasm: false
      path: "../wasm_modules/pkg/wasm_modules_bg.wasm"
      # currently this module needs to be called bin-wasm-app
      # for the core.js to load it properly
      id: "bin-wasm-app"
      compression: "brotli"

      
