[package]
name = "jsonpbp-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
